lot of fixes and gave on dynamic obmenu for now :(

diff --git a/local/.local/share/openbox/pipes/ac-sysinfo b/local/.local/share/openbox/pipes/ac-sysinfo
--- a/local/.local/share/openbox/pipes/ac-sysinfo
+++ b/local/.local/share/openbox/pipes/ac-sysinfo
@@ -1,14 +1,11 @@
 #!/usr/bin/env bash
 
-## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
-## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3
-
 ## Openbox Pipemenu to display system stats/info
 
 # Variables and functions
-MENUS_LIBDIR='/usr/share/archcraft/openbox/menulib'
-if ! . "$MENUS_LIBDIR/archcraft.cfg" 2> /dev/null; then
-	echo "Error: Failed to locate archcraft.cfg in $MENUS_LIBDIR" >&2
+MENUS_LIBDIR='$HOME/.local/share/openbox/menulib'
+if ! . "$MENUS_LIBDIR/openbox.cfg" 2> /dev/null; then
+	echo "Error: Failed to locate openbox.cfg in $MENUS_LIBDIR" >&2
 	exit 1
 fi
 
